// Title
// Type (1 = both, 2 = player only, 3 = monster only)
// Description
// Point change
// Gold worth
let deck = {
  1: ['A Full Pint', 1 , "Much like a potion, it grants you strong powers for a short time... and a bit of a headache.", 2, 4],
  2: ['A Full Pint', 1 , "Much like a potion, it grants you strong powers for a short time... and a bit of a headache.", 2, 4],
  3: ['A Full Pint', 1 , "Much like a potion, it grants you strong powers for a short time... and a bit of a headache.", 2, 4],
  4: ['A Full Pint', 1 , "Much like a potion, it grants you strong powers for a short time... and a bit of a headache.", 2, 4],
  5: ['A Full Pint', 1 , "Much like a potion, it grants you strong powers for a short time... and a bit of a headache.", 2, 4],
  6: ['A Full Pint', 1 , "Much like a potion, it grants you strong powers for a short time... and a bit of a headache.", 2, 4],
  7: ['A Full Pint', 1 , "Much like a potion, it grants you strong powers for a short time... and a bit of a headache.", 2, 4],
  8: ['Crystal of Fortitude', 1 , "If nothing else, it makes for a shiny room decoration.", 5, 10],
  9: ['Crystal of Fortitude', 1 , "If nothing else, it makes for a shiny room decoration.", 5, 10],
  10: ['Crystal of Fortitude', 1 , "If nothing else, it makes for a shiny room decoration.", 5, 10],
  11: ['Crystal of Fortitude', 1 , "If nothing else, it makes for a shiny room decoration.", 5, 10],
  12: ['Crystal of Fortitude', 1 , "If nothing else, it makes for a shiny room decoration.", 5, 10],
  13: ['Crystal of Fortitude', 1 , "If nothing else, it makes for a shiny room decoration.", 5, 10],
  14: ['Crystal of Fortitude', 1 , "If nothing else, it makes for a shiny room decoration.", 5, 10],
  15: ['Mysterious Potion', 1 , "Legally, we cannot recommend drinking this.", 4, 8],
  16: ['Mysterious Potion', 1 , "Legally, we cannot recommend drinking this.", 4, 8],
  17: ['Mysterious Potion', 1 , "Legally, we cannot recommend drinking this.", 4, 8],
  18: ['Mysterious Potion', 1 , "Legally, we cannot recommend drinking this.", 4, 8],
  19: ['Mysterious Potion', 1 , "Legally, we cannot recommend drinking this.", 4, 8],
  20: ['Mysterious Potion', 1 , "Legally, we cannot recommend drinking this.", 4, 8],
  21: ['Mysterious Potion', 1 , "Legally, we cannot recommend drinking this.", 4, 8],
  22: ['Banana Peel', 1 , "How careless to just leave this lying around?", -3, 4],
  23: ['Banana Peel', 1 , "How careless to just leave this lying around?", -3, 4],
  24: ['Banana Peel', 1 , "How careless to just leave this lying around?", -3, 4],
  25: ['Banana Peel', 1 , "How careless to just leave this lying around?", -3, 4],
  26: ['Banana Peel', 1 , "How careless to just leave this lying around?", -3, 4],
  27: ['Banana Peel', 1 , "How careless to just leave this lying around?", -3, 4],
  28: ['Banana Peel', 1 , "How careless to just leave this lying around?", -3, 4],
  29: ['Emerald Feather', 1 , "Perhaps you'll be luckier than the bird this once belonged to.", 1, 2],
  30: ['Emerald Feather', 1 , "Perhaps you'll be luckier than the bird this once belonged to.", 1, 2],
  31: ['Emerald Feather', 1 , "Perhaps you'll be luckier than the bird this once belonged to.", 1, 2],
  32: ['Emerald Feather', 1 , "Perhaps you'll be luckier than the bird this once belonged to.", 1, 2],
  33: ['Emerald Feather', 1 , "Perhaps you'll be luckier than the bird this once belonged to.", 1, 2],
  34: ['Emerald Feather', 1 , "Perhaps you'll be luckier than the bird this once belonged to.", 1, 2],
  35: ['Emerald Feather', 1 , "Perhaps you'll be luckier than the bird this once belonged to.", 1, 2],
  36: ['Health Potion', 1 , "* side effects stull unstudied", 2, 1],
  37: ['Health Potion', 1 , "* side effects stull unstudied", 2, 1],
  38: ['Health Potion', 1 , "* side effects stull unstudied", 2, 1],
  39: ['Health Potion', 1 , "* side effects stull unstudied", 2, 1],
  40: ['Health Potion', 1 , "* side effects stull unstudied", 2, 1],
  41: ['Health Potion', 1 , "* side effects stull unstudied", 2, 1],
  42: ['Health Potion', 1 , "* side effects stull unstudied", 2, 1],
  43: ['A Full Pint', 1 , "Much like a potion, it grants you strong powers for a short time... and a bit of a headache.", 2, 4],
  44: ['A Full Pint', 1 , "Much like a potion, it grants you strong powers for a short time... and a bit of a headache.", 2, 4],
  45: ['A Full Pint', 1 , "Much like a potion, it grants you strong powers for a short time... and a bit of a headache.", 2, 4]
};
